[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --chdir feedback_app --bind 0.0.0.0:$PORT app:app --workers 4 --timeout 120"
healthcheckPath = "/api/feedback"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

